language: node_js
node_js:
  - '18'
  - '20'
  - '22'

cache:
  directories:
    - node_modules

script:
  - npm run type-check
  - npm run lint
  - npm run test
  - npm run build

before_script:
  - npm run generate-mock-data
