/* eslint-disable no-console */
/* This script generates mock data for your local development.
   This way you don't have to point to an actual API,
   but you can enjoy realistic, but randomized data,
   and rapid page loads due to local, static data.
 */

import { JSONSchemaFaker as jsf } from 'json-schema-faker'
import { schema } from './mockDataSchema.js'
import { faker } from '@faker-js/faker'
import fs from 'fs'
import chalk from 'chalk'

// With latest version of json-schema-faker, must explicitly extend JSF with the fake libs you want to use.
jsf.extend('faker', () => faker)

const json = JSON.stringify(jsf.generate(schema), null, 2)

fs.writeFile('./src/api/db.json', json, function (err) {
  if (err) {
    return console.log(chalk.red(err))
  } else {
    console.log(chalk.green(`Data generated by using JSONSchemaFaker Version: ${jsf.VERSION}`))
    console.log(chalk.green('Mock data generated.'))
  }
})
